package com.example.mechrevo.myapplication.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.mechrevo.myapplication.bean.HisData;

import com.example.mechrevo.myapplication.bean.HisDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hisDataDaoConfig;

    private final HisDataDao hisDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hisDataDaoConfig = daoConfigMap.get(HisDataDao.class).clone();
        hisDataDaoConfig.initIdentityScope(type);

        hisDataDao = new HisDataDao(hisDataDaoConfig, this);

        registerDao(HisData.class, hisDataDao);
    }
    
    public void clear() {
        hisDataDaoConfig.clearIdentityScope();
    }

    public HisDataDao getHisDataDao() {
        return hisDataDao;
    }

}
